### ISSUE TITLE
Game crashes by pressing "Options" in main menu

### ISSUE THREAD

**Issue by koutoftimer** [IlyaFaer/ForwardOnlyGame#142]
Steps to reproduce:

* Download and extract latest GNU\Linux release tar ball.
* Lauch game and press "Options" button.

Error message:

```
$ ./Forward\ Only 
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "direct.showbase.EventManager", line 49, in eventLoopTask
  File "direct.showbase.EventManager", line 43, in doEvents
  File "direct.showbase.EventManager", line 99, in processEvent
  File "direct.showbase.Messenger", line 337, in send
  File "direct.showbase.Messenger", line 422, in __dispatch
  File "direct.gui.DirectButton", line 107, in commandFunc
  File "gui", line 341, in _show_conf
ValueError: tuple.index(x): x not in tuple
:task(error): Exception occurred in PythonTask eventManager
```
System info:
```
$ uname -a
Linux k53ta 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux```

**Comment by IlyaFaer** [comment]
Hello, @koutoftimer. Thanks for filling this issue!

Would you mind sending me your `options.cfg` file? Seems like problem is somewhere there.
The file lives in the game directory.

**Comment by koutoftimer** [comment]
@IlyaFaer I haven't changed anything. It should be default one. First thing I did was pressing that "Options" button.

**Comment by IlyaFaer** [comment]
@koutoftimer, it works this way:

- when you start the game first time it measures your screen resolution and puts it into the config file
- then, when you open Options menu, the game reads these configurations and fills the menu. On this step a list of supported resolutions is used, and your `1366x768` is not in this list

I'll add your resolution into the list shortly (the next release is planned in July, so if you're using the game build, it'll take some time to get the fix). Right now, as a dirty hack, you can redact the config file and set resolution to one of these:

https://github.com/IlyaFaer/ForwardOnlyGame/blob/1ff34fad7d41a1a8b176d91c6ea9ccb041ea292b/gui/__init__.py#L32-L42

That should unblock the Options menu for you.
